name: Build APK
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install buildozer cython
      - run: sudo apt update && sudo apt install -y autoconf automake libtool libffi-dev libltdl-dev
      - run: buildozer android debug
      - uses: actions/upload-artifact@v4
        with:
          name: APK
          path: bin/*.apk
